### ISSUE TITLE
Multiple calls mocks.

### ISSUE THREAD

**Issue by nrxus** [nrxus/faux#2]
Currently when we set up a mock:
```rust
unsafe { when!(my_mock.some_method).then(|_| { /* do things */} )
```

It sets up a **one time mock**, which means that after the mock is invoked, next time it runs the code will panic saying that no mock was set. 

This library should support mocks that are set up once and run multiple times, either a set number of times, or forever.

**Comment by nrxus** [comment]
Calling a mock multiple times can be achieved by either:
- Having the closure implement clone, which means that any captured data must also implement clone.
- Moving away from `FnOnce` and towards `FnMut`. This means that any captured data could at most be mutably borrowed and not moved. 

I am unsure which one of these two approaches is the most limiting to an user.

**Comment by nrxus** [comment]
Another thing to keep in mind, do we want to keep the `FnOnce` without clone behavior for the edge cases where the mock needs to move data that cannot be cloned? Or should that just be removed until I come across an scenario that actually wants this.

**Comment by TedDriggs** [comment]
Could you add a new method, `.always(...)` which had the `Clone` constraint?

**Comment by nrxus** [comment]
Yes, that's a possibility. 

The biggest two things stopping me from implementing this are:
* I haven't run into a use case for this yet in my personal projects so I don't know what the API should be like. Also with `faux` being pretty new there aren't enough users for me to try and get a feel of what users of faux would want.
* I am unsure how clone (or FnMut) mocks should interact with the one time mocks. Should one override the other, just do a latest first, should they both co-exist somehow....? All this uncertainty has stopped me from implementing it.

At some point even without feedback I will move on and just do whatever feels right at the moment but for now I am trying to see if something comes up that guides my decision.

**Comment by TedDriggs** [comment]
I'd suggest that an active `when` mock overrules a standing `always` mock.

**Comment by audunhalland** [comment]
+1 for multiple calls. Currently cannot switch to faux exclusively because of this.

**Comment by nrxus** [comment]
I am prioritizing this as my next thing to tackle after https://github.com/nrxus/faux/issues/10

**Comment by nrxus** [comment]
fixed in: https://github.com/nrxus/faux/commit/a2fc133fa0a2079feef8a42cc4bbea564a51c0b0

I will close this after doing a new release... which should be soon.

**Comment by nrxus** [comment]
v0.0.4 is released with this feature :tada:
