### ISSUE TITLE
Support traits with pinned self type

### ISSUE THREAD

**Issue by Wesmania** [nrxus/faux#29]
I have a type that implements `tokio::io::AsyncRead` and I'd like to use faux with it. The trait uses `Pin<&mut Self>` as a self type, and faux doesn't have that variant.  I prepared a bare minimum prototype that adds it. I know little about pinning, but I think it shouldn't cause much trouble with mocks.

**Comment by nrxus** [comment]
How is your `Pin` getting created? Is it a `Pin<Box<T>>` or is the pointer inside the `Pin` something else?

**Comment by Wesmania** [comment]
That trait mentioned above uses `Pin<&mut T>`.

**Comment by nrxus** [comment]
re-opening until this the changes that fix this issue are released not just committed.

**Comment by nrxus** [comment]
Released in v0.0.7
