### ISSUE TITLE
not compatible with rust-annalyze

### ISSUE THREAD

**Issue by xiaoquanju** [nrxus/faux#48]
i think faux is a very good mock lib, but not compatible with rust-annalyze sometimes;
![16546711476251](https://user-images.githubusercontent.com/47780062/172551187-56000c37-60ea-4ef3-9396-b609c5f0c53d.png)

erros tips is :
1, missing structure fields: 0
2,no field `running_task_num` on type `&SessionManager` available fields are: `0`

**Comment by xiaoquanju** [comment]
i find that the object create must be in aux_method.   close

**Comment by nrxus** [comment]
@xiaoquanju yes, `faux` wants every method that reads/writes the fields of the actual struct to be wrapped by `faux_methods`. I am glad you got it figured it out!
