### ISSUE TITLE
Better Errors

### ISSUE THREAD

**Issue by nrxus** [nrxus/faux#7]
Better macro expansion compiler errors. 

Do as much as we can while compiling on stable.

Also investigate these nightly features `proc_macro_diagnostic` & `proc_macro_def_site` as ways of better compiler errors. Might be worth having a nightly feature in the crate that enables these features for better compiler errors.

**Comment by nrxus** [comment]
Investigate: https://gitlab.com/CreepySkeleton/proc-macro-error

**Comment by TedDriggs** [comment]
Now that you’re using `darling`, would its errors do what you need?
